let APPDATA = JSON.parse(localStorage.getItem("customDataFinal") || "null") || DATA;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let allLessons=APPDATA.stages.flatMap(s=>s.lessons);let lastPage="home";let currentLessonId=null;
const state={done:JSON.parse(localStorage.getItem("doneFinal")||"[]"),wrong:JSON.parse(localStorage.getItem("wrongFinal")||"[]"),fav:JSON.parse(localStorage.getItem("favFinal")||"[]"),tasks:JSON.parse(localStorage.getItem("tasksFinal")||"{}"),notes:JSON.parse(localStorage.getItem("notesFinal")||"{}")};
function save(){localStorage.setItem("doneFinal",JSON.stringify(state.done));localStorage.setItem("wrongFinal",JSON.stringify(state.wrong));localStorage.setItem("favFinal",JSON.stringify(state.fav));localStorage.setItem("tasksFinal",JSON.stringify(state.tasks));localStorage.setItem("notesFinal",JSON.stringify(state.notes))}
function page(id){if(id!=="lesson")lastPage=id;$$(".page").forEach(p=>p.classList.toggle("active",p.id===id));$$("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));if(id==="admin")dataPreview.value=JSON.stringify(APPDATA,null,2)}
function unlocked(id){return id===1||state.done.includes(id-1)||state.done.includes(id)}
function progress(){const c=state.done.length;$("#progressText").textContent=`已完成 ${c} / ${allLessons.length} 关`;$("#progressBar").style.width=Math.round(c/allLessons.length*100)+"%";let lv="Lv1 电脑新手";if(c>=90)lv="Lv10 独立部署者";else if(c>=80)lv="Lv9 项目实战者";else if(c>=70)lv="Lv8 安全巡检员";else if(c>=60)lv="Lv7 初级运维师";else if(c>=50)lv="Lv6 Docker 训练生";else if(c>=40)lv="Lv5 建站新手";else if(c>=30)lv="Lv4 服务器操作者";else if(c>=20)lv="Lv3 终端学徒";else if(c>=10)lv="Lv2 网络入门者";$("#levelName").textContent=lv;dailyList.innerHTML=[`继续完成第 ${Math.min(c+1,allLessons.length)} 关`,`复习 ${Math.min(3,APPDATA.commands.length)} 条收藏/常用命令`,`打开 1 个排查案例练习`].map(x=>`<li>${x}</li>`).join("")}
function renderMap(){stageList.innerHTML=APPDATA.stages.map(s=>`<div class="stage"><div class="stage-head"><div><h3>${s.title}</h3><small>${s.desc}</small></div><small>${s.lessons.filter(l=>state.done.includes(l.id)).length}/${s.lessons.length}</small></div><div class="lesson-grid">${s.lessons.map(l=>`<div class="lesson-item ${state.done.includes(l.id)?"done":""} ${unlocked(l.id)?"":"locked"}" data-id="${l.id}"><b>第 ${l.id} 关 ${state.done.includes(l.id)?"✓":unlocked(l.id)?"":"🔒"}</b><h4>${l.title}</h4><p>${l.minutes} 分钟 · ${"★".repeat(l.difficulty)}${"☆".repeat(5-l.difficulty)}</p></div>`).join("")}</div></div>`).join("");$$(".lesson-item").forEach(el=>el.onclick=()=>{const id=+el.dataset.id;if(!unlocked(id))return alert("先完成上一关，再解锁本关。");openLesson(id)})}
function renderRoutes(){routeList.innerHTML=APPDATA.routes.map(r=>{let ids=APPDATA.stages.filter(s=>r.stageIds.includes(s.id)).flatMap(s=>s.lessons.map(l=>l.id));let done=ids.filter(id=>state.done.includes(id)).length;return `<div class="card"><span class="tag">${done}/${ids.length}</span><h3>${r.title}</h3><p>${r.desc}</p><div class="progress"><span style="width:${Math.round(done/ids.length*100)}%"></span></div><br><button onclick="openLesson(${ids.find(id=>!state.done.includes(id)&&unlocked(id))||ids[0]})">开始/继续</button></div>`}).join("")}
function openLesson(id){currentLessonId=id;const l=allLessons.find(x=>x.id===id);page("lesson");const taskKey="l"+id;const checked=state.tasks[taskKey]||[];lessonContent.innerHTML=`<h2>第 ${l.id} 关：${l.title}</h2><div class="meta"><span class="pill">难度 ${"★".repeat(l.difficulty)}${"☆".repeat(5-l.difficulty)}</span><span class="pill">预计 ${l.minutes} 分钟</span><span class="pill">${l.topic}</span></div><p>${l.story}</p><h3>知识讲解</h3>${l.explain.map(x=>`<p>${x}</p>`).join("")}${l.commands.length?`<h3>核心命令</h3><pre>${esc(l.commands.join("\n"))}</pre>`:""}<h3>速记卡</h3><div class="cheat">${l.cheat.map(x=>`<p>${x}</p>`).join("")}</div><h3>任务清单</h3><div class="tasks">${l.tasks.map((t,i)=>`<label><input type="checkbox" data-task="${i}" ${checked.includes(i)?"checked":""}/> ${t}</label>`).join("")}</div><h3>本关笔记</h3><textarea class="notearea" id="lessonNote" placeholder="记录你自己的理解、服务器命令、踩坑点...">${esc(state.notes[taskKey]||"")}</textarea><div class="quiz"><h3>通关测试</h3>${l.quiz.map((q,qi)=>`<div class="qblock" data-q="${qi}"><p>${qi+1}. ${q[0]}</p>${q[1].map((o,i)=>`<button class="option" data-q="${qi}" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join("")}</div>`).join("")}<p id="quizResult"></p></div>`;$$("[data-task]").forEach(cb=>cb.onchange=()=>{state.tasks[taskKey]=$$("[data-task]").filter(x=>x.checked).map(x=>+x.dataset.task);save()});lessonNote.oninput=e=>{state.notes[taskKey]=e.target.value;save();renderNotes()};let answered={};$$(".option").forEach(btn=>btn.onclick=()=>{const qi=+btn.dataset.q,i=+btn.dataset.i,q=l.quiz[qi],ok=i===q[2];answered[qi]=ok;$$(`.option[data-q="${qi}"]`).forEach((b)=>{b.disabled=true;if(+b.dataset.i===q[2])b.classList.add("correct")});if(!ok){btn.classList.add("wrong");if(!state.wrong.find(w=>w.id===l.id&&w.q===q[0]))state.wrong.push({id:l.id,title:l.title,q:q[0],a:q[1][q[2]]})}if(Object.keys(answered).length===l.quiz.length){const pass=Object.values(answered).every(Boolean);quizResult.innerHTML=pass?'<span style="color:var(--green)">全部答对，已通关。</span>':'<span style="color:var(--red)">有题答错，已加入错题本。也可以继续下一关。</span>';if(!state.done.includes(l.id))state.done.push(l.id);save();renderAll()}else save()})}
function renderCommands(k=""){let list=APPDATA.commands.filter(c=>!k||JSON.stringify(c).toLowerCase().includes(k.toLowerCase()));commandList.innerHTML=list.map(c=>`<div class="card"><button class="fav" onclick="toggleFav('${c.name.replaceAll("'","\\'")}')">${state.fav.includes(c.name)?"★":"☆"}</button><span class="tag">${c.cat}</span><h3>${c.name}</h3><p>${c.desc}</p><pre>${esc(c.example)}</pre></div>`).join("")}
function toggleFav(n){state.fav=state.fav.includes(n)?state.fav.filter(x=>x!==n):[...state.fav,n];save();renderCommands(commandSearch.value)}
function renderTroubles(){troubleList.innerHTML=APPDATA.troubles.map(t=>`<div class="card"><span class="tag">${t.tags.join(" / ")}</span><h3>${t.title}</h3><h4>排查步骤</h4><ol class="step">${t.steps.map(s=>`<li>${s}</li>`).join("")}</ol><pre>${esc(t.commands.join("\n"))}</pre></div>`).join("")}
function renderProjects(){projectList.innerHTML=APPDATA.projects.map(p=>`<div class="card"><span class="tag">${p.level}</span><h3>${p.title}</h3><p>${p.desc}</p><ol class="step">${p.steps.map(s=>`<li>${s}</li>`).join("")}</ol><p><b style="color:var(--green)">验收：</b>${p.check}</p></div>`).join("")}
function renderGlossary(k=""){let list=APPDATA.glossary.filter(g=>!k||JSON.stringify(g).toLowerCase().includes(k.toLowerCase()));glossaryList.innerHTML=list.map(g=>`<div class="card"><h3>${g.term}</h3><p>${g.desc}</p></div>`).join("")}
function renderWrong(){wrongList.innerHTML=state.wrong.length?state.wrong.map(w=>`<div class="card"><span class="tag">第 ${w.id} 关</span><h3>${w.title}</h3><p>${w.q}</p><p><b style="color:var(--green)">正确答案：</b>${w.a}</p></div>`).join(""):`<div class="card"><p>暂无错题。</p></div>`}
function renderNotes(){const entries=Object.entries(state.notes).filter(([k,v])=>v.trim());notesList.innerHTML=entries.length?entries.map(([k,v])=>{let id=+k.replace("l",""),l=allLessons.find(x=>x.id===id);return `<div class="card"><span class="tag">第 ${id} 关</span><h3>${l?l.title:"笔记"}</h3><p>${esc(v).replaceAll("\n","<br>")}</p></div>`}).join(""):`<div class="card"><p>暂无笔记。</p></div>`}
function renderAchievements(){let marks=[3,10,20,30,40,50,60,70,80,100],names=["电脑新手","网络入门者","终端学徒","服务器操作者","建站新手","Docker 训练生","初级运维师","安全巡检员","项目实战者","独立部署者"];achievementList.innerHTML=names.map((n,i)=>`<div class="card ${state.done.length>=marks[i]?"":"lock"}"><div class="badge">${state.done.length>=marks[i]?"✓":"?"}</div><h3>${n}</h3><p>完成 ${marks[i]} 关解锁</p></div>`).join("")}
function renderSearch(k=""){if(!k){searchResults.innerHTML='<div class="card"><p>输入关键词开始搜索课程、命令、故障、项目和术语。</p></div>';return}k=k.toLowerCase();let arr=[];allLessons.filter(l=>JSON.stringify(l).toLowerCase().includes(k)).slice(0,10).forEach(l=>arr.push(`<div class="card"><span class="tag">课程</span><h3>第 ${l.id} 关：${l.title}</h3><p>${l.explain[0]}</p><button onclick="openLesson(${l.id})">打开</button></div>`));APPDATA.commands.filter(c=>JSON.stringify(c).toLowerCase().includes(k)).slice(0,10).forEach(c=>arr.push(`<div class="card"><span class="tag">命令</span><h3>${c.name}</h3><p>${c.desc}</p><pre>${esc(c.example)}</pre></div>`));APPDATA.troubles.filter(t=>JSON.stringify(t).toLowerCase().includes(k)).forEach(t=>arr.push(`<div class="card"><span class="tag">故障</span><h3>${t.title}</h3><p>${t.steps[0]}</p></div>`));APPDATA.projects.filter(p=>JSON.stringify(p).toLowerCase().includes(k)).forEach(p=>arr.push(`<div class="card"><span class="tag">项目</span><h3>${p.title}</h3><p>${p.desc}</p></div>`));APPDATA.glossary.filter(g=>JSON.stringify(g).toLowerCase().includes(k)).forEach(g=>arr.push(`<div class="card"><span class="tag">术语</span><h3>${g.term}</h3><p>${g.desc}</p></div>`));searchResults.innerHTML=arr.join("")||'<div class="card"><p>没有找到相关内容。</p></div>'}
function renderAll(){allLessons=APPDATA.stages.flatMap(s=>s.lessons);progress();renderMap();renderRoutes();renderCommands(commandSearch?.value||"");renderTroubles();renderProjects();renderGlossary(glossarySearch?.value||"");renderWrong();renderNotes();renderAchievements();renderSearch(globalSearch?.value||"");if(dataPreview)dataPreview.value=JSON.stringify(APPDATA,null,2)}
function download(name,obj){const blob=new Blob([typeof obj==="string"?obj:JSON.stringify(obj,null,2)],{type:"application/json;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function readJson(file,cb){const r=new FileReader();r.onload=()=>{try{cb(JSON.parse(r.result))}catch(e){alert("JSON 格式错误")}};r.readAsText(file)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
$$('#nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$$('[data-jump]').forEach(b=>b.onclick=()=>page(b.dataset.jump));backBtn.onclick=()=>page(lastPage);continueBtn.onclick=()=>{let n=allLessons.find(l=>!state.done.includes(l.id)&&unlocked(l.id))||allLessons[0];openLesson(n.id)};commandSearch.oninput=e=>renderCommands(e.target.value);globalSearch.oninput=e=>renderSearch(e.target.value);glossarySearch.oninput=e=>renderGlossary(e.target.value);clearWrong.onclick=()=>{state.wrong=[];save();renderWrong()};exportNotes.onclick=()=>download("notes.json",state.notes);exportData.onclick=()=>download("it-quest-data.json",APPDATA);exportProgress.onclick=()=>download("it-quest-progress.json",state);importData.onchange=e=>{let f=e.target.files[0];if(f)readJson(f,obj=>{APPDATA=obj;localStorage.setItem("customDataFinal",JSON.stringify(obj));renderAll();alert("数据已导入")})};importProgress.onchange=e=>{let f=e.target.files[0];if(f)readJson(f,obj=>{Object.assign(state,obj);save();renderAll();alert("进度已导入")})};resetBtn.onclick=()=>{if(confirm("确定重置本地进度、错题、收藏、任务和笔记吗？课程数据不会删除。")){state.done=[];state.wrong=[];state.fav=[];state.tasks={};state.notes={};save();renderAll();page("home")}};if("serviceWorker"in navigator){addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}))}renderAll();
